export const animation = [
    {
        el: '#nail1',
        origin: 'bottom right',
        duration: 0.4,
        delay: 0.6,
        ease: 'elastic.out(1.3, .6)',
    },
    {
        el: '#nail2',
        origin: 'bottom left',
        duration: 0.4,
        delay: 0.7,
        ease: 'elastic.out(1.3, .6)',
    },
    {
        el: '#nail3',
        origin: 'bottom center',
        duration: 0.4,
        delay: 0.8,
        ease: 'elastic.out(1.3, .6)',
    },
    {
        el: '#nail4',
        origin: 'bottom right',
        duration: 0.4,
        delay: 0.9,
        ease: 'elastic.out(1.3, .6)',
    },
    {
        el: '#nail5',
        origin: 'bottom right',
        duration: 0.4,
        delay: 1,
        ease: 'elastic.out(1.3, .6)',
    },
    {
        el: '#feuille1',
        origin: 'bottom left',
        duration: 0.4,
        delay: 1.9,
        ease: 'elastic.out(1.3, .6)',
    },
    {
        el: '#feuille2',
        origin: 'top right',
        duration: 0.4,
        delay: 2,
        ease: 'elastic.out(1.3, .6)',
    },
    {
        el: '#feuille3',
        origin: 'top right',
        duration: 0.4,
        delay: 2.1,
        ease: 'elastic.out(1.3, .6)',
    },
    {
        el: '#feuille4',
        origin: 'bottom left',
        duration: 0.4,
        delay: 2.2,
        ease: 'elastic.out(1.3, .6)',
    },
    {
        el: '#feuille5',
        origin: 'top right',
        duration: 0.4,
        delay: 2.3,
        ease: 'elastic.out(1.3, .6)',
    },
    {
        el: '#feuille6',
        origin: 'bottom left',
        duration: 0.4,
        delay: 2.4,
        ease: 'elastic.out(1.3, .6)',
    },
    {
        el: '#feuille7',
        origin: 'top right',
        duration: 0.4,
        delay: 2.5,
        ease: 'elastic.out(1.3, .6)',
    },
    {
        el: '#feuille8',
        origin: 'bottom right',
        duration: 0.4,
        delay: 2.5,
        ease: 'elastic.out(1.3, .6)',
    },
    {
        el: '#star',
        origin: 'center',
        duration: 0.4,
        delay: 2.8,
        ease: 'elastic.out(1.3, .6)',
    },
    {
        el: '#bigStar',
        origin: 'center',
        duration: 0.4,
        delay: 3,
        ease: 'elastic.out(1.3, .6)',
    },
];
export const slide = {
    initial: {
        y: 0,
        clipPath: 'ellipse(100% 55% at 48% 44%)',
    },
    exit: {
        y: '-110vh',
        clipPath: 'ellipse(0% 0% at 0% 0%)',
        transition: { duration: 0.5, ease: 'anticipate', delay: 0.2 },
    },
};
